M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu24.04.1} date 2024-10-06T17:11:56+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-06T17:11:56+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.450
%
G90
G05
T1
X113.0Y-41.0
X113.0Y-136.0
X177.0Y-41.0
X177.0Y-136.05
T2
X153.0Y-135.93
T3
X153.0Y-72.4
X169.0Y-127.6
M30
